name: 🐛 Bug Report
description: Report a bug or unexpected behavior in PDF4QT
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: A clear description of what you expected
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: A clear description of what actually happened
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: PDF4QT Version
      description: What version of PDF4QT are you running?
      options:
        - v1.6.0 (latest)
        - v1.5.x
        - v1.4.x
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (Ubuntu/Debian)
        - Linux (Fedora/RHEL)
        - Linux (Arch)
        - Linux (Other)
      multiple: false
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Specific OS version (e.g., "Windows 11 23H2", "macOS 14.2", "Ubuntu 22.04")
      placeholder: e.g., Windows 11 23H2
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Does this happen with all PDF files or specific ones?
        - Did this work in a previous version?
        - Are you using the floating toolbar feature?
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
